version: '3.8'

services:
  web:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "8080:80"
    volumes:
      - /site:/usr/share/nginx/html:ro
      - /nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
