version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: static_site
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
